### ISSUE TITLE
Error: unrecognized flag --no-opt

### ISSUE THREAD

**Issue by eftikharEmad** [npm/documentation#982]
Hello, 
we are getting this error when we try to install bower with npm , on docker with base image ruby-2.3.0
```
  => [rmdc_backend_app  4/18] RUN rm /etc/apt/sources.list                                                                                                           0.3s
  => [rmdc_backend_app  5/18] RUN echo "deb http://archive.debian.org/debian/ jessie main" | tee -a /etc/apt/sources.list                                            0.2s
   => [rmdc_backend_app  6/18] RUN echo "deb-src http://archive.debian.org/debian/ jessie main" | tee -a /etc/apt/sources.list                                        0.3s
 => [rmdc_backend_app  7/18] RUN echo "Acquire::Check-Valid-Until false;" | tee -a /etc/apt/apt.conf.d/10-nocheckvalid                                              0.3s
 => [rmdc_backend_app  8/18] RUN echo 'Package: *\nPin: origin "archive.debian.org"\nPin-Priority: 500' | tee -a /etc/apt/preferences.d/10-archive-pin              0.3s
 => [rmdc_backend_app  9/18] RUN apt-get update                                                                                                                     7.3s
 => [rmdc_backend_app 10/18] RUN apt-get install -yq --force-yes build-essential git libpq-dev libmysqlclient-dev libav-tools libxml2-dev libxslt-dev nodejs-lega  38.8s
 => [rmdc_backend_app 11/18] RUN apt-get install -yq --force-yes npm                                                                                               18.9s
 => ERROR [rmdc_backend_app 12/18] RUN npm install -g bower                                                                                                         0.6s
------
 > [rmdc_backend_app 12/18] RUN npm install -g bower:
0.314 Error: unrecognized flag --no-opt
0.314 Try --help for options
0.561
0.563 module.js:340
0.565     throw err;
0.565           ^
0.592 Error: Cannot find module 'process'
0.592     at Function.Module._resolveFilename (module.js:338:15)
0.592     at Function.Module._load (module.js:280:25)
0.592     at Module.require (module.js:364:17)
0.592     at require (module.js:380:17)
0.592     at Object.<anonymous> (/proc/.reset:1:71)
0.592     at Module._compile (module.js:456:26)
0.592     at Object.Module._extensions..js (module.js:474:10)
0.592     at Module.load (module.js:356:32)
0.592     at Function.Module._load (module.js:312:12)
0.592     at Function.Module.runMain (module.js:497:10)
------
failed to solve: process "/bin/sh -c npm install -g bower" did not complete successfully: exit code: 8
```
any Idea how to solve it ? and remove the place that call this option ?

**Comment by ljharb** [comment]
What node and npm version is being used?

Either way, bower is long since dead and deprecated afaik. What do you need it for?

**Comment by wraithgar** [comment]
Please use the issue template

**Comment by eftikharEmad** [comment]
I need  (last value recorded) ```node -v => v14.17.6```, ```npm -v  ===> 5.6.0```

we need to install bower , so I used this in dockerfile 
```
SHELL ["/bin/bash", "--login", "-i", "-c"]
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh | bash
RUN source /root/.bashrc && nvm install node
SHELL ["/bin/bash", "--login", "-c"]
```

but bower is not define in the entrypoint.sh

here is my old lines
```
RUN rm /etc/apt/sources.list
RUN echo "deb http://archive.debian.org/debian/ jessie main" | tee -a /etc/apt/sources.list
RUN echo "deb-src http://archive.debian.org/debian/ jessie main" | tee -a /etc/apt/sources.list
RUN echo "Acquire::Check-Valid-Until false;" | tee -a /etc/apt/apt.conf.d/10-nocheckvalid
RUN echo 'Package: *\nPin: origin "archive.debian.org"\nPin-Priority: 500' | tee -a /etc/apt/preferences.d/10-archive-pin
RUN apt-get update

RUN apt-get install -yq --force-yes \
build-essential \
git \
libpq-dev \
libmysqlclient-dev \
libav-tools \
libxml2-dev \
libxslt-dev \
nodejs-legacy \
imagemagick \
tzdata \
&& rm -rf /var/cache/apt/* \
&& mkdir -p $APP_PATH

RUN apt-get install -yq --force-yes npm
RUN npm install -g bower

RUN echo '{ "allow_root": true }' > /root/.bowerrc
```

in entrypoint.sh
 ```
bower cache clean
bower install --save moment
```
